def Students():
    students=[
        {
            'id':1,
            'name':'gokul',
            'place':'ksd',
            'mobileno':7558867988,
            'email':'gokulmelath@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':2,
            'name':'sreevin',
            'place':'knnr',
            'mobileno':7558867999,
            'email':'gh@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':3,
            'name':'arun',
            'place':'kollam',
            'mobileno':7558866666,
            'email':'arun@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':4,
            'name':'arjun',
            'place':'mumbai',
            'mobileno':9876543256,
            'email':'arjun@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':5,
            'name':'ujwal',
            'place':'cltct',
            'mobileno':755856789,
            'email':'uk@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':6,
            'name':'athul',
            'place':'knnr',
            'mobileno':678965799,
            'email':'abc@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':7,
            'name':'anand',
            'place':'dubai',
            'mobileno':7558867943,
            'email':'annd@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':8,
            'name':'abhi',
            'place':'tvm',
            'mobileno':984568757,
            'email':'abhi@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':9,
            'name':'aswin',
            'place':'ksd',
            'mobileno':765432188,
            'email':'aswin88@gmail.com',
            'joindate':'06/10/2018'
        },
        {
            'id':10,
            'name':'sayanth',
            'place':'palkd',
            'mobileno':987635656,
            'email':'gm@gmail.com',
            'joindate':'06/10/2018'
        }
    ]
    return students